repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-merge-conflict
          - id: check-toml
          - id: check-yaml
          - id: debug-statements
          - id: end-of-file-fixer
          - id: no-commit-to-branch
          - id: trailing-whitespace
    - repo: https://github.com/psf/black
      rev: '23.3.0'
      hooks:
        - id: black
          types_or: [python, pyi]
          language_version: python3
    - repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
        - id: isort
          args: [--settings-file, ./pyproject.toml]
    - repo: https://github.com/PyCQA/docformatter
      rev: v1.7.1
      hooks:
        - id: docformatter
          additional_dependencies: [tomli]
          args: [--in-place, --config, ./pyproject.toml]
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: 'v0.0.269'
      hooks:
        - id: ruff
          args: [ --select, "PL", --select, "F" ]
    - repo: https://github.com/pycqa/pydocstyle
      rev: 6.3.0
      hooks:
        - id: pydocstyle
          additional_dependencies: [toml]
          args: [--config, ./pyproject.toml]
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.3.0
      hooks:
        - id: mypy
          additional_dependencies: [types-python-dateutil]
          args: [--config-file, ./pyproject.toml]
    - repo: https://github.com/myint/eradicate
      rev: '2.2.0'
      hooks:
        - id: eradicate
          args: []
    - repo: https://github.com/rstcheck/rstcheck
      rev: 'v6.1.2'
      hooks:
        - id: rstcheck
          additional_dependencies: [tomli]
          args: [-r, --config, ./pyproject.toml]
