# This workflow runs when a pull request is closed.
#
# - Gets list of PR labels.
# - IF 'release' label:
#   - Get release version using Poetry.
#   - Get next semantic version.
#   - Close old milestones.
#   - Create new minor version milestone.
#   - Create new major version milestone.
name: Do Release Workflow

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  create_new_milestone:
    name: Create New Milestone
    needs: cut-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get PR labels
        id: prlabels
        uses: joerick/pr-labels-action@v1.0.6

      - name: Get release version
        id: relversion
        if: contains(steps.prlabels.outputs.labels, ' release ')
        run: |
          pip install poetry
          echo "version=$(echo $(poetry version | cut -d' ' -f2))" >> $GITHUB_OUTPUT
          echo "do_milestones=1" >> $GITHUB_ENV

      - name: Get next semantic version
        id: nextversion
        if: ${{ env.do_milestones == 1 }}
        uses: WyriHaximus/github-action-next-semvers@v1.1.0
        with:
          version: ${{ steps.relversion.outputs.version }}

      - name: Close old milestone
        if: ${{ env.do_milestones == 1 }}
        uses: WyriHaximus/github-action-close-milestone@master
        with:
          number: ${{ steps.relversion.outputs.version }}

      - name: Create new minor release milestone
        if: ${{ env.do_milestones == 1 }}
        uses: WyriHaximus/github-action-create-milestone@v1.2.0
        with:
          title: "${{ steps.nextversion.outputs.v_minor }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new major release milestone
        if: ${{ env.do_milestones == 1 }}
        uses: WyriHaximus/github-action-create-milestone@v1.2.0
        with:
          title: "${{ steps.nextversion.outputs.v_major }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
