# This workflow runs when a version tag is pushed.
#
# - Get new tag.
# - If release condidate tag:
#   - Cut GitHub pre-release.
name: Prerelease Tag Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  cut_prerelease:
    permissions:
      contents: write
      pull-requests: write
    name: Cut Pre-Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Get new tag
        id: newversion
        run: |
          tag=${GITHUB_REF/refs\/tags\//}
          if [[ $tag == *"-rc"* ]]; then
            echo "do_prerelease=1" >> $GITHUB_ENV
          fi
          echo "tag=$(echo $tag)" >> $GITHUB_ENV
          echo "New tag is: $tag"
          echo "GitHub ref: ${{ github.ref }}"

      - name: Cut pre-release
        id: cutprerelease
        if: ${{ env.build_ok == 1 }}
        uses: release-drafter/release-drafter@v5
        with:
          name: ${{ env.tag }}
          tag: ${{ env.tag }}
          version: ${{ env.tag }}
          prerelease: true
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
